### ISSUE TITLE
Exception occurred in processing next value of Perfmon Counter:

### ISSUE THREAD

**Issue by ingersal** [newrelic/nri-perfmon#28]
We do see this exception in event viewer. Can someone please help me

Exception occurred in processing next value of Perfmon Counter:
Category: ASP.NET Applications
Counter: Transactions/Sec
Message: Instance '_LM_W3SVC_6_ROOT_bposervice' does not exist in the specified Category.
Trace:    at System.Diagnostics.CounterDefinitionSample.GetInstanceValue(String instanceName)
   at System.Diagnostics.PerformanceCounter.NextSample()
   at System.Diagnostics.PerformanceCounter.NextValue()
   at NewRelic.PerfmonPlugin.PollPerfCounters() in Z:\eclipse\nri-perfmon\nri-perfmon\Plugin.cs:line 510

**Comment by sschwartzman** [comment]
This was fixed in a recent release, can you try the latest out?

https://github.com/newrelic/nri-perfmon/releases/tag/0.6.1

**Comment by sschwartzman** [comment]
@ingersal closing due to inactivity, we can re-open if you still have the issue after trying the latest release
