### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by david-garcia-garcia** [newrelic/nri-perfmon#45]
message:Application: nri-perfmon.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.ThrowHelper.ThrowInvalidOperationException(System.ExceptionResource)
   at System.Collections.Generic.Dictionary`2+KeyCollection+Enumerator[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at NewRelic.PerfmonPlugin.PollPerfCounters()
   at NewRelic.RemoteUser.RunAsRemoteUser[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Func`1<System.__Canon>)
   at NewRelic.PerfmonPlugin.RunThread()
   at NewRelic.Program.Main(System.String[])

**Comment by david-garcia-garcia** [comment]
The exception message seems to be swallowed in the application's error handling some way, but looking at the implementation this totally might be due to iterating the keys of a dictionary and the dictionary being mutated (either from within the loop or another thread).

**Comment by david-garcia-garcia** [comment]
https://github.com/newrelic/nri-perfmon/pull/46

**Comment by jbeveland27** [comment]
Fixed in #46.
